export const dummyNotes = [
  { _id: "1", title: "Note 1", desc: "Description for Note 1" },
  {
    _id: "2",
    title: "How to Cook?",
    desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like. ",
  },
  { _id: "3", title: "Note 3", desc: "Description for Note 3" },
  { _id: "4", title: "Note 4", desc: "Description for Note 4" },
  { _id: "5", title: "Note 5", desc: "Description for Note 5" },
  { _id: "6", title: "Note 6", desc: "Description for Note 6" },
  { _id: "7", title: "Note 7", desc: "Description for Note 7" },
  { _id: "8", title: "Note 8", desc: "Description for Note 8" },
  { _id: "9", title: "Note 9", desc: "Description for Note 9" },
  { _id: "10", title: "Note 10", desc: "Description for Note 10" },
  { _id: "11", title: "Note 11", desc: "Description for Note 11" },
  { _id: "12", title: "Note 12", desc: "Description for Note 12" },
  { _id: "13", title: "Note 13", desc: "Description for Note 13" },
  { _id: "14", title: "Note 14", desc: "Description for Note 14" },
  { _id: "15", title: "Note 15", desc: "Description for Note 15" },
  { _id: "16", title: "Note 16", desc: "Description for Note 16" },
  { _id: "17", title: "Note 17", desc: "Description for Note 17" },
  { _id: "18", title: "Note 18", desc: "Description for Note 18" },
  { _id: "19", title: "Note 19", desc: "Description for Note 19" },
  { _id: "20", title: "Note 20", desc: "Description for Note 20" },
];
